services:
  mysql:
    container_name: fitDay-mysql
    image: mysql:8
    ports:
      - "3308:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/csv:/var/lib/mysql-files
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    container_name: fitDay-redis
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - ./db/redis/data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 5