version: "3.3"

services:
  mysql:
    container_name: fitDay-mysql
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    environment:
      TZ: "Asia/Seoul"
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: fitDay
      MYSQL_USER: test1234
      MYSQL_PASSWORD: test1234
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - fitday-network

  redis:
    container_name: fitDay-redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis/data:/data
    command: redis-server --appendonly yes
    environment:
      TZ: "Asia/Seoul"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 5
    networks:
      - fitday-network

  github-actions:
    container_name: github-actions
    image: 390402538983.dkr.ecr.ap-northeast-2.amazonaws.com/github-actions:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fitDay
#      - SPRING_DATASOURCE_USERNAME=test1234
#      - SPRING_DATASOURCE_PASSWORD=test1234
    networks:
      - fitday-network

# 외부 network 사용할때 external true / docker-compose 안에서 네트워크 형성하면 bridge 사용
networks:
  fitday-network:
    external: true