version: '3.3'
services:
  redis:
    container_name: fitDay-redis
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - ./db/redis/data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 5
    networks:
      - fitday-network

  github-actions:
    image: ${API_SERVER_IMAGE}
    container_name: github-actions
    ports:
      - "8082:8080"
    networks:
      - fitday-network
    volumes:
      - /home/ubuntu/pinpoint:/home/ubuntu/pinpoint:ro
    entrypoint:
      - java
    command:
      - -javaagent:/home/ubuntu/pinpoint/pinpoint-bootstrap.jar
      - -Dpinpoint.config=/home/ubuntu/pinpoint/pinpoint-root.config
      - -Dpinpoint.agentId=fitday
      - -Dpinpoint.applicationName=fitday-app
      - -Dspring.profiles.active=dev
      - -jar
      - /app.jar

networks:
  fitday-network:
    external: true