version: "3.3"
services:
  mysql:
    container_name: fitDay-mysql
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      TZ: "Asia/Seoul"
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: fitDay
      MYSQL_USER: test1234
      MYSQL_PASSWORD: test1234
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - fitday-network

  redis:
    container_name: fitDay-redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis/data:/data
    command: redis-server --appendonly yes
    environment:
      TZ: "Asia/Seoul"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 5
    networks:
      - fitday-network

  github-actions:
    container_name: github-actions
    image: 390402538983.dkr.ecr.ap-northeast-2.amazonaws.com/github-actions:latest
    ports:
      - 8080:8080
    restart: always
    networks:
      - fitday-network
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: 'default'

networks:
  fitday-network:
    external: true