version: "3"

services:
  nginxproxy:
    image: nginx:latest
    container_name: proxyserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./scripts/fitday.conf:/etc/nginx/nginx.conf
      - ./certbot-etc:/etc/letsencrypt
      - ./web:/usr/share/nginx/html

  certbot:
    depends_on:
      - nginxproxy
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./web:/usr/share/nginx/html
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email test@test.com --agree-tos --no-eff-email --keep-until-expiring -d fitday.site -d www.fitday.site

  mysql:
    depends_on:
      - nginxproxy
    container_name: fitDay-mysql
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      TZ: "Asia/Seoul"
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: fitDay
      MYSQL_USER: test1234
      MYSQL_PASSWORD: test1234
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    depends_on:
      - nginxproxy
    container_name: fitDay-redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis/data:/data
    command: redis-server --appendonly yes
    environment:
      TZ: "Asia/Seoul"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 5

